image: docker:stable
services:
  - docker:dind

variables:
  GITLAB_TAG: $CI_REGISTRY_IMAGE
  HUB_TAG: prantlf/node-git-chromium

build:
  script:
    - |
      docker run --rm -i \
        -v "${PWD}"/.hadolint.yaml:/.config/hadolint.yaml \
        hadolint/hadolint < Dockerfile
    - docker build -t $GITLAB_TAG .
    - docker tag $GITLAB_TAG $GITLAB_TAG:lts-alpine
    - docker tag $GITLAB_TAG $HUB_TAG
    - docker tag $HUB_TAG $HUB_TAG:lts-alpine
    - echo -n "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker push $GITLAB_TAG
    - docker push $GITLAB_TAG:lts-alpine
    - |
      mkdir -p $HOME/.docker
      echo '{ "auths": { "'https://index.docker.io/v1/'": { "auth": "'$DOCKER_AUTH'", "email": "prantlf@gmail.com" } } }' \
        > $HOME/.docker/config.json
    - docker push $HUB_TAG
    - docker push $HUB_TAG:lts-alpine
